apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: deploy
  namespace: argocd # Make sure this matches your Argo CD namespace
spec:
  clusterResourceWhitelist:
    - group: rbac.authorization.k8s.io
      kind: ClusterRole
    - group: rbac.authorization.k8s.io
      kind: ClusterRoleBinding
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
  description: Ghost Blog project
  destinations:
    - name: "*"
      namespace: "*"
      server: https://kubernetes.default.svc
  roles:
    - name: deploy-app
      groups:
        - devs # Replace with your actual Kubernetes group
  sourceRepos:
    - "*" # Replace with your Git repo URL for security

